BEGIN;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
  );

-- CREATE TYPE walkthrough_type AS ENUM (
--   'monsters',
--   'limits',
--   'weapons',
--   'materia'
-- );

-- CREATE TABLE walkthroughs (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   user_id INTEGER REFERENCES users(id) NOT NULL,
--   name TEXT NOT NULL,
--   type walkthrough_type NOT NULL,
--   reference INTEGER NOT NULL,
--   body TEXT NOT NULL
-- );

CREATE TABLE monsters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  name TEXT NOT NULL UNIQUE,
  hp INTEGER NOT NULL,
  mp INTEGER NOT NULL,
  exp INTEGER NOT NULL,
  ap INTEGER NOT NULL,
  gil INTEGER NOT NULL,
  weakness TEXT NOT NULL,
  strength TEXT NOT NULL,
  location TEXT NOT NULL,
  level INTEGER NOT NULL,
  steal TEXT NOT NULL,
  drops TEXT NOT NULL,
  morph TEXT NOT NULL,
  enemy_skill TEXT NOT NULL,
  walkthrough TEXT
);

CREATE TABLE guides (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  monster_id INTEGER REFERENCES monsters(id) NOT NULL,
  name TEXT NOT NULL,
  note TEXT NOT NULL,
  walkthrough TEXT
  );

CREATE TABLE limits (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  character TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  level INTEGER NOT NULL,
  walkthrough TEXT
);

CREATE TYPE materia_type AS ENUM (
  'command',
  'summon',
  'magic',
  'support',
  'independent'
)

CREATE TABLE materia (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type materia_type NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  walkthrough TEXT
);

CREATE TABLE weapons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  character TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  walkthrough TEXT
);

COMMIT;