BEGIN;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
  );

CREATE TABLE monsters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  hp INTEGER NOT NULL,
  mp INTEGER NOT NULL,
  exp INTEGER NOT NULL,
  ap INTEGER NOT NULL,
  gil INTEGER NOT NULL,
  weakness TEXT NOT NULL,
  strength TEXT NOT NULL,
  location TEXT NOT NULL,
  level INTEGER NOT NULL,
  steal TEXT NOT NULL,
  drops TEXT NOT NULL,
  morph TEXT NOT NULL,
  enemy_skill TEXT NOT NULL
);

CREATE TABLE limits (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  character TEXT NOT NULL,
  name TEXT NOT NULL,
  level INTEGER NOT NULL,
  description TEXT NOT NULL,
  obtain_by TEXT NOT NULL
);

CREATE TYPE materia_type AS ENUM (
  'command',
  'summon',
  'magic',
  'support',
  'independent'
);

CREATE TABLE materia (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type materia_type NOT NULL,
  description TEXT NOT NULL,
  skills TEXT ARRAY DEFAULT ARRAY[]::TEXT[],
  ap INTEGER ARRAY DEFAULT ARRAY[]::INTEGER[] NOT NULL,
  mp INTEGER ARRAY DEFAULT ARRAY[]::INTEGER[],
  sell INTEGER NOT NULL,
  location TEXT NOT NULL
);

CREATE TABLE weapons (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  character TEXT NOT NULL,
  location TEXT NOT NULL,
  slots INTEGER NOT NULL,
  growth TEXT NOT NULL
);

CREATE TYPE walkthrough_type AS ENUM (
  'monsters',
  'limits',
  'weapons',
  'materia'
);

CREATE TABLE walkthroughs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type walkthrough_type NOT NULL,
  monster_id INTEGER REFERENCES monsters(id),
  weapon_id INTEGER REFERENCES weapons(id),
  limit_id INTEGER REFERENCES limits(id),
  materia_id INTEGER REFERENCES materia(id),
  user_name TEXT REFERENCES users(user_name) NOT NULL,
  body VARCHAR NOT NULL
);

CREATE TABLE guides (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  walkthrough_id INTEGER REFERENCES walkthroughs(id) NOT NULL,
  name TEXT NOT NULL,
  note TEXT
  );

COMMIT;