CREATE TABLE 
  ff7oa_guides (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES ff7oa_users(id) NOT NULL,
    monster_id INTEGER REFERENCES ff7oa_monsters(id) NOT NULL,
    name TEXT NOT NULL,
    note TEXT NOT NULL
  );